Hi there! This is advertisements project which i made for 3.5 hours. I thought, i could make user sign up/login system but it was too little time(it can be made in future)

if i had 1-2 more hours i could make better design, but now sorting and pagination works perfectly. I made all project from scratch, havn't looking for any solution in stackoverflow, my past projects etc.

That's all for now, i'm going to publish it on github.
