Hi there! This is advertisements project which i made for 2 hours. I thought, i could made user sign up/login system but it was too little time so i even havn't finished post publication :c 

if i had 1-2 more hours i could make better design and post publisment, but now sorting and pagination works perfectly. I made all project from scratch, havn't looking for any solution in stackoverflow, my past projects etc.

That's all for now, i'm going to publish it on github. Current time: 17:58